version: "3.1"

# todo - persist the db between start/stop cycles.

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todd-coin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
