version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todd-coin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    image: tbrunia/todd-coin:latest
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_NAME: todd-coin
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432
      API_HOST: 0.0.0.0
      API_PORT: 3000
volumes:
  pgdata:
